# Keyboard name
CONFIG_ZMK_KEYBOARD_NAME="Zyra FT"

# BT - transmit power
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# Sleep
CONFIG_ZMK_SLEEP=y

# ZMK Studio (the cradio shield already has the 'studio' feature upstream)
CONFIG_ZMK_STUDIO=y

# Eager debouncing (as in other FT keyboards)
CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=1
CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=7
